### PR TITLE
feat(AChatAttachment): basic logic for interaction with Helia nodes

### PR DESCRIPTION
**Pull request by bludnic**

### CODE REVIEW

**Comment by bludnic** [comment]
@RealGoodProgrammer Fix build error https://github.com/Adamant-im/adamant-im/actions/runs/8756718576/job/24033802576

**Comment by bludnic** [comment]
App broken when attaching files with a reply message:

image

**Comment by bludnic** [comment]
Another error 
image

**Comment by bludnic** [comment]
Fix the errors above and test it properly:

1. Open iOS app
2. Send a message with files attachment
2. Reply to a message and attach some files
3. Open PWA
4. Open same chat
5. Verify that there are no errors, and attachment type transactions are normalized correctly

@RealGoodProgrammer

**Comment by RealGoodProgrammer** [comment]
@bludnic Try it on MacOS now. At the same time I'll try it on Ubuntu

**Pull request merged**
