### PR TITLE
fix: ws is trying to connect to not supported node and the app uses this node for REST requests

### PR DESCRIPTION
**Pull request by PaulDremanovich**

### CODE REVIEW

**Comment by PaulDremanovich** [comment]
[Bug: Ws is trying to connect to Not supported node (screenshot. )I also see the app uses this node for REST requests.](https://trello.com/c/8LMF9tyv/499-bug-ws-is-trying-to-connect-to-not-supported-node-screenshot-i-also-see-the-app-uses-this-node-for-rest-requests)

**Comment by adamant-al** [comment]
@martiliones @bludnic 
Ready for test?

**Comment by adamant-al** [comment]
@PaulDremanovich 
Why don't you merge?

**Review by bludnic — APPROVED** [review]

**Comment by adamant-al** [comment]
@bludnic Can we merge?
I want it in the current release.

**Comment by RealGoodProgrammer** [comment]
I'll gonna decline this PR because it is buggy (infinite spinner in chat). It will be done in a scope of this [task](https://trello.com/c/1mmlJa1I)

**Comment by RealGoodProgrammer** [comment]
@adamant-al I'm gonna close this PR because it is buggy. For this feature we made a new task

**Pull request closed without merging**
