### PR TITLE
Kucoin support

### PR DESCRIPTION
**Pull request by MaaKut**

### CODE REVIEW

**Comment by bludnic** [comment]
Everything looks fine. One more thing need to do here to make the cryptocurrency visible in the chat.

https://github.com/Adamant-im/adamant-im/blob/dev/src/lib/chatHelpers.js#L158-L162
```
kcs_transaction: 'KCS'
```

**Comment by adamant-al** [comment]
Please take new KuCoin logo as here https://coinmarketcap.com/currencies/kucoin-shares/
(Grayscale)

**Comment by adamant-al** [comment]
Wrong amounts for KCS in Transaction list
6 decimals for KCS in MEW

**Comment by adamant-al** [comment]
When sending KuCoin and other ERC20-tokens, fee must count in ETH, but not in KCS, etc.

**Pull request merged**
