### PR TITLE
Moment sending funds

### PR DESCRIPTION
**Pull request by onemorejsdeveloper**

### CODE REVIEW

**Comment by Elena-Andreeva** [comment]
1.	Messages with ETH, BNB appears in chat only 3-5 seconds left after sending
2.	It is possible to send  0 BNB and 0 ETH. Usual fee is charged for them. 
3.	It’s impossible to send 0 ADM. But system notification is “Error while sending transaction”. Better: “Amount couldn’t be 0”
4.	Common note: translation into German, French, Arabian (?) isn’t complete. Still there are menu items on English.

**Comment by Elena-Andreeva** [comment]
1. Sent messages mark as 'recieved' in common chat
2. Possible to send 0 ADM by resending
Video (mpeg4): https://drive.google.com/file/d/13Plpw2msGYztx9k9h99N4Lood8wpXnOb/view?usp=sharing

**Comment by Elena-Andreeva** [comment]
1. There are no sound notification and mark when recieve ADM
Usual: http://dl3.joxi.net/drive/2018/11/20/0021/3536/1424848/48/9e8bcb0d60.jpg
ADM: http://dl3.joxi.net/drive/2018/11/20/0021/3536/1424848/48/583f0f06a7.jpg
2.Messages with ADM and BNB in-chat appears with delay

**Comment by adamant-al** [comment]
-3
Received ADM in chat dialog should also be shown with status (done).

Remove "done" checkboxed form other received messages, needed for transfers only.

In the list of chats, received transfers should look like "recived-checkbox", not "checkbox, received" in order not to mess sent and received.

**Comment by adamant-al** [comment]
Broken: All sent messages should have delivery statuses.

**Comment by Elena-Andreeva** [comment]
Error when open page Vote for delegate (opens after reload only)
http://dl4.joxi.net/drive/2018/11/26/0021/3536/1424848/48/36ca7e3d6d.jpg

**Comment by adamant-al** [comment]
> Error when open page Vote for delegate (opens after reload only)
> http://dl4.joxi.net/drive/2018/11/26/0021/3536/1424848/48/36ca7e3d6d.jpg

I think master-branch should be merged and it will be fixed.

**Pull request merged**
