### PR TITLE
Feature/binance coin

### PR DESCRIPTION
**Pull request by MaaKut**

### CODE REVIEW

**Comment by adamant-al** [comment]
1. 
Add " (Ether)" to Fee filed name, when transfrerring ERC20 tokens. 
Now:
Комиссия за перевод
0,000126
To be:
Комиссия за перевод (Ether)
0,000126

1.1 
Fee for transfreering ETH is 0,0021
Fee for transfreering BNB is 0,0105
Why differs so much? 0,01 ETH is $3

1.2 
Fix "Max" value of Amount to send:
If < 0, then = 0;

2. Not resolved.

3. Not resolved.

4. Need to test later.

5. In Send In-Chat (BNB first time)
"To Field": No address
! We solved same bug months ago for ETH. Ask @zyuhel 
If than choose Send ETH, and than BNB again — no bug.

6. If no ETH address in KVS, no message about that (both for ETH and BNB).

7. While sending BNB, check ETH balance to pay comission
Fire Snackbar:
You need also ETH to pay transfer fee
Вам также нужно ETH для оплаты комиссии

**Comment by MaaKut** [comment]
Merged the latest changes from `master`, added fixes for the above mentioned issues.

**Comment by adamant-al** [comment]
-1.1) Not resolved.
Fee for transfreering ETH is 0,0013
Fee for transfreering BNB is 0,013
Why differs x10?

-1.2) Not resolved.
Fix "Max" value of Amount to send:
If < 0, then = 0;

-1.3)
Send funds button: fix styles
Transfer confirmation request buttons: fix styles

2) Cannot test. See 5.1.

3) Cannot test. See 5.1.

-4) Cannot test. See 5.1.

-5) No comments field for Send BNB

-5.1) 
erc20-actions.js:135 Failed to send BNB transaction Error: exceeds block gas limit

-6) Not resolved.
If no ETH address in KVS, no message about that (both for ETH and BNB).

-7) Now: transfer.error_erc20_fee
Should be:
You need also ETH to pay transfer fee
Вам также нужно ETH для оплаты комиссии

-8) No icons on Wallet Screen

**Comment by adamant-al** [comment]
-1.3)
Send funds button: fix styles
Transfer confirmation request buttons: fix styles

-2) Cannot test. See 5.1.
After sending BNB Tx, transactions details do not update:
Количество | ⏳
Подтверждений | ⏳

-3) Cannot test. See 5.1.
Tx details screen shows
Комиссия за перевод | 0.0063 ETH
But on Etherscan I see Actual Tx Cost/Fee: 0.00157542 Ether ($0.45)
https://etherscan.io/tx/0xe732c5762892e54f2d018dc7b463137c7a965122c63e1f4060eba944e480ec98

-4) Cannot test. See 5.1.
When making payment, I see
Комиссия за перевод (ETH)
0,000126
But Tx details: Actual Tx Cost/Fee: 0.00157542 Ether
Why it is differs x10?

-5.1) Not resolved.
erc20-actions.js:135 Failed to send BNB transaction Error: exceeds block gas limit
ETH transactions also do not work on https://feature-binance_coin-branch-adamant-im.surge.sh/
Same error.
While on live it is working.

-6) Not resolved.
If no ETH address in KVS, no message about that (both for ETH and BNB).
Try to message U3258175327744161633 (have no public KVS record for ETH), and than Send ETH in-Chat

**Pull request merged**
